export default {
  kind: "customsearch#search",
  url: {
    type: "application/json",
    template:
      "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json",
  },
  queries: {
    request: [
      {
        title: "Google Custom Search - sdfg",
        totalResults: "6",
        searchTerms: "sdfg",
        count: 6,
        startIndex: 1,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "a2acee15487090aa8",
      },
    ],
  },
  context: {
    title: "Google",
  },
  searchInformation: {
    searchTime: 0.472587,
    formattedSearchTime: "0.47",
    totalResults: "6",
    formattedTotalResults: "6",
  },
  items: [
    {
      kind: "customsearch#result",
      title: "asda sdfg fs",
      htmlTitle: "asda <b>sdfg</b> fs",
      link: "https://www.google.com/podcasts?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy80NmU3MmYyMC9wb2RjYXN0L3Jzcw==",
      displayLink: "www.google.com",
      snippet:
        "Jan 9, 2021 ... asda sdfg fs. adsfa adfsg f. asda sdfg fs. Subscribe. Visit website. subscribe to this \nwww.youtube.com/watch?v=xs_FQTkz3JM. Available ...",
      htmlSnippet:
        "Jan 9, 2021 <b>...</b> asda <b>sdfg</b> fs. adsfa adfsg f. asda <b>sdfg</b> fs. Subscribe. Visit website. subscribe to this <br>\nwww.youtube.com/watch?v=xs_FQTkz3JM. Available&nbsp;...",
      cacheId: "tgkTtKqA-coJ",
      formattedUrl: "https://www.google.com/podcasts?feed...",
      htmlFormattedUrl: "https://www.google.com/podcasts?feed...",
      pagemap: {
        metatags: [
          {
            "og:image":
              "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQEsEgNgyLkBCYWLZ9I-b7V6zhswb5T45PHXyYTTz6_3lexdJpe",
            "apple-itunes-app":
              "app-id=1398000105, affiliate-data=ct=podcastsSmartBannerShow001&pt=9008, app-argument=https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy80NmU3MmYyMC9wb2RjYXN0L3Jzcw",
            "og:type": "music.radio_station",
            "twitter:card": "summary",
            "twitter:title": "asda sdfg fs",
            "og:site_name": "Google Podcasts",
            "og:title": "asda sdfg fs",
            "music:creator": "asda sdfg fs",
            title: "asda sdfg fs",
            "og:description":
              "subscribe to this www.youtube.com/watch?v=xs_FQTkz3JM",
            "twitter:creator": "asda sdfg fs",
            "article:author": "asda sdfg fs",
            "twitter:image":
              "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQEsEgNgyLkBCYWLZ9I-b7V6zhswb5T45PHXyYTTz6_3lexdJpe",
            referrer: "origin",
            viewport:
              "width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no,minimal-ui",
            "og:url":
              "https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy80NmU3MmYyMC9wb2RjYXN0L3Jzcw",
          },
        ],
        cse_image: [
          {
            src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQEsEgNgyLkBCYWLZ9I-b7V6zhswb5T45PHXyYTTz6_3lexdJpe",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title:
        "US20060242617A1 - Automatic generation of streaming processor ...",
      htmlTitle:
        "US20060242617A1 - Automatic generation of streaming processor ...",
      link: "https://www.google.com/patents/US20060242617",
      displayLink: "www.google.com",
      snippet:
        "4 , following start block 402, a streaming data flow graph (SDFG) description of \nan algorithm kernel is loaded at block 404. At block 406 a set of circuit constraints \nis ...",
      htmlSnippet:
        "4 , following start block 402, a streaming data flow graph (<b>SDFG</b>) description of <br>\nan algorithm kernel is loaded at block 404. At block 406 a set of circuit constraints <br>\nis&nbsp;...",
      formattedUrl: "https://www.google.com/patents/US20060242617",
      htmlFormattedUrl: "https://www.google.com/patents/US20060242617",
      pagemap: {
        metatags: [
          {
            referrer: "origin-when-crossorigin",
            citation_patent_application_number: "US:11/109,915",
            "dc.description":
              "A streaming processor circuit of a processing system is automatically generated by selecting a set of circuit parameters consistent with a set of circuit constraints and generating a representation of a candidate streaming processor circuit based upon the set of circuit parameters to execute one or more iterations of a computation specified by a streaming data flow graph. The candidate streaming processor circuit is evaluated with respect to one or more quality metrics and the representation of the candidate streaming processor circuit is output if the candidate streaming processor circuit satisfies a set of processing system constraints and is better in at least one of the one or more quality metrics than other candidate streaming processor circuits.",
            citation_patent_publication_number: "US:20060242617:A1",
            "dc.type": "patent",
            viewport: "width=device-width, initial-scale=1",
            "dc.relation": "US:5535319",
            "dc.title":
              "Automatic generation of streaming processor architectures",
            citation_pdf_url:
              "https://patentimages.storage.googleapis.com/f9/a9/cf/f570259a34d9fa/US20060242617A1.pdf",
            "dc.date": "2005-04-20",
            "dc.contributor": "Nikos Bellas",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "Google Maps",
      htmlTitle: "Google Maps",
      link: "https://www.google.com/maps/contrib/111408902415595969835/reviews",
      displayLink: "www.google.com",
      snippet:
        "sdfg. Like Share. Photo of Shri Shyam Hotel And Restaurant. Shri Shyam Hotel \nAnd Restaurant. Harota, Chomu, Rajasthan 303702, India -. 2 months ago. New.",
      htmlSnippet:
        "<b>sdfg</b>. Like Share. Photo of Shri Shyam Hotel And Restaurant. Shri Shyam Hotel <br>\nAnd Restaurant. Harota, Chomu, Rajasthan 303702, India -. 2 months ago. New.",
      cacheId: "ifQtGC6F5v8J",
      formattedUrl:
        "https://www.google.com/maps/contrib/111408902415595969835/reviews",
      htmlFormattedUrl:
        "https://www.google.com/maps/contrib/111408902415595969835/reviews",
      pagemap: {
        cse_thumbnail: [
          {
            src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSnvOWa__nknQDPhRK3biydCez_GcRd6HdMu0Y6vHm6pF4ps-rQyn4wCEiB",
            width: "310",
            height: "163",
          },
        ],
        metatags: [
          {
            referrer: "origin",
            "og:image":
              "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_3.png",
            "og:image:width": "256",
            "twitter:card": "summary",
            "og:site_name": "Contributions by Krrish Jangir",
            viewport:
              "initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no",
            "og:title": "Contributions by Krrish Jangir",
            "og:image:height": "256",
            google: "notranslate",
            "og:description": "Level 3 Local Guide | 135 Points",
          },
        ],
        place: [
          {
            image:
              "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_3.png",
            name: "Contributions by Krrish Jangir",
            description: "Level 3 Local Guide | 135 Points",
          },
        ],
        cse_image: [
          {
            src: "https://maps.gstatic.com/tactile/geoprofile/sharing/lg_3.png",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "Xxx",
      htmlTitle: "Xxx",
      link: "https://www.google.com/podcasts?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy8zNTE4ZjM1MC9wb2RjYXN0L3Jzcw==",
      displayLink: "www.google.com",
      snippet:
        "Sdfg. Xxx. Subscribe. Visit website. Charla común entre amigos. Available \nepisodes. Oct 18, 2020. Amigos . 1 hr. Search. Clear search. Close search.",
      htmlSnippet:
        "<b>Sdfg</b>. Xxx. Subscribe. Visit website. Charla común entre amigos. Available <br>\nepisodes. Oct 18, 2020. Amigos . 1 hr. Search. Clear search. Close search.",
      cacheId: "xK-xq4CkOD0J",
      formattedUrl: "https://www.google.com/podcasts?feed...",
      htmlFormattedUrl: "https://www.google.com/podcasts?feed...",
      pagemap: {
        metatags: [
          {
            "og:image":
              "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT3q6_NDxn8m5rpeyi829PZ8Pud2Rv7YjFXc8ejL6sPKhDK-bW6",
            "apple-itunes-app":
              "app-id=1398000105, affiliate-data=ct=podcastsSmartBannerShow001&pt=9008, app-argument=https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy8zNTE4ZjM1MC9wb2RjYXN0L3Jzcw",
            "og:type": "music.radio_station",
            "twitter:card": "summary",
            "twitter:title": "Xxx",
            "og:site_name": "Google Podcasts",
            "og:title": "Xxx",
            "music:creator": "Xxx",
            title: "Xxx",
            "og:description": "Charla común entre amigos",
            "twitter:creator": "Xxx",
            "article:author": "Xxx",
            "twitter:image":
              "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT3q6_NDxn8m5rpeyi829PZ8Pud2Rv7YjFXc8ejL6sPKhDK-bW6",
            referrer: "origin",
            viewport:
              "width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no,minimal-ui",
            "og:url":
              "https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy8zNTE4ZjM1MC9wb2RjYXN0L3Jzcw",
          },
        ],
        cse_image: [
          {
            src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT3q6_NDxn8m5rpeyi829PZ8Pud2Rv7YjFXc8ejL6sPKhDK-bW6",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "Fête de la musique : à Lyon, l'éclectisme est au rendez-vous",
      htmlTitle:
        "Fête de la musique : à Lyon, l&#39;éclectisme est au rendez-vous",
      link: "https://www.google.com/appserve/mkt/p/AJ-PF7xC8vtx69c6yk6mA0k3mbOXd_7qIsJ1_JRgDv8sb6_wg1ErozrzNyHVRaWOWar_fYeEt9FkeigzdHZjxikN0fMDtVbPRIPtKaDtrvbgAOR653oGH4Qps1cJC4BtICUD1_3Mmcno1QcA9DuhNx3Y-59-i4ggDrT3xM4w4KOKHI0F9Ud6c3BJquk57R44Nw",
      displayLink: "www.google.com",
      snippet:
        "21 juin 2018 ... Dès 17h, la place Saint-Jean saura attirer les curieux avec un panel d'artistes d'\nhorizons musicaux divers : SDFG fera des reprises des années ...",
      htmlSnippet:
        "21 juin 2018 <b>...</b> Dès 17h, la place Saint-Jean saura attirer les curieux avec un panel d&#39;artistes d&#39;<br>\nhorizons musicaux divers : <b>SDFG</b> fera des reprises des années&nbsp;...",
      cacheId: "8oo0R3041N0J",
      formattedUrl:
        "https://www.google.com/.../AJ-PF7xC8vtx69c6yk6mA0k3mbOXd_7qIsJ1_ JRgDv8sb6_wg1ErozrzNyHVRaWOWar_ ...",
      htmlFormattedUrl:
        "https://www.google.com/.../AJ-PF7xC8vtx69c6yk6mA0k3mbOXd_7qIsJ1_ JRgDv8sb6_wg1ErozrzNyHVRaWOWar_ ...",
      pagemap: {
        cse_thumbnail: [
          {
            src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSrjKIUfXZOwmHgpv1MHheu2_CjKVuir3JxrtrJ78f3pcGmzUUvc-L8MEg",
            width: "262",
            height: "193",
          },
        ],
        metatags: [
          {
            "og:image":
              "https://www.lyoncapitale.fr/wp-content/uploads/2014/06/460500-ez-Fete-de-la-musique-795x585.jpg",
            "og:type": "article",
            "article:published_time": "2018-06-21T08:18:41Z",
            "twitter:card": "summary",
            "twitter:title":
              "Fête de la musique : à Lyon, l'éclectisme est au rendez-vous",
            "og:site_name": "Lyon Capitale",
            "og:title":
              "Fête de la musique : à Lyon, l'éclectisme est au rendez-vous",
            "msapplication-tileimage":
              "https://www.lyoncapitale.fr/wp-content/uploads/2019/09/favicolc192.png",
            "og:description":
              "Solstice d'été, nouvelle Fête de la musique. Avec un programme riche et varié dans les neuf arrondissements de Lyon. Ce jeudi 21 juin, les artistes, pros ou amateurs, rythmeront la journée la plus longue de l'année dans l'espace public lyonnais.",
            "og:image:secure_url":
              "https://www.lyoncapitale.fr/wp-content/uploads/2014/06/460500-ez-Fete-de-la-musique-795x585.jpg",
            "twitter:image":
              "https://www.lyoncapitale.fr/wp-content/uploads/2014/06/460500-ez-Fete-de-la-musique-795x585.jpg",
            "article:tag": "été",
            "fb:app_id": "292626204198836",
            "twitter:site": "@lyoncap",
            "article:modified_time": "2018-06-21T12:07:24Z",
            viewport: "initial-scale=1, maximum-scale=1",
            "twitter:description":
              "Solstice d'été, nouvelle Fête de la musique. Avec un programme riche et varié dans les neuf arrondissements de Lyon. Ce jeudi 21 juin, les artistes, pros ou amateurs, rythmeront la journée la plus longue de l'année dans l'espace public lyonnais.",
            "og:url":
              "https://www.lyoncapitale.fr/culture/fete-de-la-musique-a-lyon-leclectisme-est-au-rendez-vous/",
          },
        ],
        cse_image: [
          {
            src: "https://www.lyoncapitale.fr/wp-content/uploads/2014/06/460500-ez-Fete-de-la-musique-795x585.jpg",
          },
        ],
      },
    },
    {
      kind: "customsearch#result",
      title: "«غرفة الشارقة» تبحث آفاق التعاون مع مدينة فروتسواف البولندية ...",
      htmlTitle:
        "«غرفة الشارقة» تبحث آفاق التعاون مع مدينة فروتسواف البولندية ...",
      link: "https://www.google.com/newsstand/s/posts/CAIiEBHVf-_gTypS8OpGZFSdyvkqGAgEKg8IACoHCAowqrmfCTDQjG8w3Z6gAQ/%C2%AB%D8%BA%D8%B1%D9%81%D8%A9+%D8%A7%D9%84%D8%B4%D8%A7%D8%B1%D9%82%D8%A9%C2%BB+%D8%AA%D8%A8%D8%AD%D8%AB+%D8%A2%D9%81%D8%A7%D9%82+%D8%A7%D9%84%D8%AA%D8%B9%D8%A7%D9%88%D9%86+%D9%85%D8%B9+%D9%85%D8%AF%D9%8A%D9%86%D8%A9+%D9%81%D8%B1%D9%88%D8%AA%D8%B3%D9%88%D8%A7%D9%81+%D8%A7%D9%84%D8%A8%D9%88%D9%84%D9%86%D8%AF%D9%8A%D8%A9",
      displayLink: "www.google.com",
      snippet:
        "13 شباط (فبراير) 2017 ... الأهلي المصري ثالث أندية العالم للمرة الثانية. sdfg. عادي. رياضة دولي · مسؤولو الكرة \nالإنجليزية يطالبون «تويتر» و«فيسبوك» بمكافحة العنصرية.",
      htmlSnippet:
        "13 شباط (فبراير) 2017 <b>...</b> الأهلي المصري ثالث أندية العالم للمرة الثانية. <b>sdfg</b>. عادي. رياضة دولي &middot; مسؤولو الكرة <br>\nالإنجليزية يطالبون «تويتر» و«فيسبوك» بمكافحة العنصرية.",
      cacheId: "4ezUpzbDyAoJ",
      formattedUrl:
        "https://www.google.com/.../«غرفة+الشارقة»+تبحث+آفاق+التعاون+مع+مدينة+ فروتسواف+البولندية",
      htmlFormattedUrl:
        "https://www.google.com/.../«غرفة+الشارقة»+تبحث+آفاق+التعاون+مع+مدينة+ فروتسواف+البولندية",
      pagemap: {
        cse_thumbnail: [
          {
            src: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRg0gJbQ25KBnxQWln3yIasInCMEGqp302H3tgF9bQQ-4ovgXpkSEKF5G4",
            width: "259",
            height: "194",
          },
        ],
        metatags: [
          {
            "og:image":
              "https://www.alkhaleej.ae/sites/default/files/styles/social_large/public/migrated/b32b0f22-16e7-4bdf-9c09-8cf8d24fecc7.jpg?itok=GKbqSqWb",
            "twitter:card": "summary_large_image",
            "og:type": "article",
            "twitter:title":
              "«غرفة الشارقة» تبحث آفاق التعاون مع مدينة فروتسواف البولندية | صحيفة الخليج",
            "og:site_name": "صحيفة الخليج",
            "og:image:url":
              "https://www.alkhaleej.ae/sites/default/files/styles/social_large/public/migrated/b32b0f22-16e7-4bdf-9c09-8cf8d24fecc7.jpg?itok=GKbqSqWb",
            handheldfriendly: "true",
            "twitter:url":
              "https://www.alkhaleej.ae/2017-02-13/%C2%AB%D8%BA%D8%B1%D9%81%D8%A9-%D8%A7%D9%84%D8%B4%D8%A7%D8%B1%D9%82%D8%A9%C2%BB-%D8%AA%D8%A8%D8%AD%D8%AB-%D8%A2%D9%81%D8%A7%D9%82-%D8%A7%D9%84%D8%AA%D8%B9%D8%A7%D9%88%D9%86-%D9%85%D8%B9-%D9%85%D8%AF%D9%8A%D9%86%D8%A9-%D9%81%D8%B1%D9%88%D8%AA%D8%B3%D9%88%D8%A7%D9%81-%D8%A7%D9%84%D8%A8%D9%88%D9%84%D9%86%D8%AF%D9%8A%D8%A9/%D8%A7%D9%82%D8%AA%D8%B5%D8%A7%D8%AF-%D9%85%D8%AD%D9%84%D9%8A",
            "og:title":
              "«غرفة الشارقة» تبحث آفاق التعاون مع مدينة فروتسواف البولندية | صحيفة الخليج",
            abstract:
              "الشارقة: «الخليج»\nاستضافت غرفة تجارة وصناعة الشارقة في مقرها الرئيسي مؤخراً، وفداً بولندياً من مدينة فروتسواف ترأسه عمدة فروتسواف «رافاو ودتكيفيتش» وذلك في إطار الجولة التي قام بها الوفد الزائر إلى إمارة الشارقة بالتعاون مع دائرة العلاقات الحكومية للاطلاع على ما تزخر به الإمارة في مجال التراث والفنون والتعليم والاستثمار.حضر اللقاء الشيخ فاهم بن سلطان بن خالد القاسمي، رئيس دائرة العلاقات الحكومية، وعبد الله سلطان العويس، رئيس غرفة تجارة وصناعة الشارقة وعدد من أعضاء مجلس الإدارة، وخالد بن بطي الهاجري مدير عام الغرفة.",
            "og:description":
              "الشارقة: «الخليج»\nاستضافت غرفة تجارة وصناعة الشارقة في مقرها الرئيسي مؤخراً، وفداً بولندياً من مدينة فروتسواف ترأسه عمدة فروتسواف «رافاو ودتكيفيتش» وذلك في إطار الجولة التي قام بها الوفد الزائر إلى إمارة الشارقة بالتعاون مع دائرة العلاقات الحكومية للاطلاع على ما تزخر به الإمارة في مجال التراث والفنون والتعليم والاستثمار.حضر اللقاء الشيخ فاهم بن سلطان بن خالد القاسمي، رئيس دائرة العلاقات الحكومية، وعبد الله سلطان العويس، رئيس غرفة تجارة وصناعة الشارقة وعدد من أعضاء مجلس الإدارة، وخالد بن بطي الهاجري مدير عام الغرفة.",
            "twitter:image":
              "https://www.alkhaleej.ae/sites/default/files/styles/social_large/public/migrated/b32b0f22-16e7-4bdf-9c09-8cf8d24fecc7.jpg?itok=GKbqSqWb",
            "og:image:secure_url":
              "https://www.alkhaleej.ae/sites/default/files/styles/social_large/public/migrated/b32b0f22-16e7-4bdf-9c09-8cf8d24fecc7.jpg?itok=GKbqSqWb",
            referrer: "origin",
            viewport: "width=device-width, initial-scale=1, shrink-to-fit=no",
            "twitter:description":
              "الشارقة: «الخليج»\nاستضافت غرفة تجارة وصناعة الشارقة في مقرها الرئيسي مؤخراً، وفداً بولندياً من مدينة فروتسواف ترأسه عمدة فروتسواف «رافاو ودتكيفيتش» وذلك في إطار الجولة التي قام بها الوفد الزائر إلى إمارة الشارقة بالتعاون مع دائرة العلاقات الحكومية للاطلاع على ما تزخر به الإمارة في مجال التراث والفنون والتعليم والاستثمار.حضر اللقاء الشيخ فاهم بن سلطان بن خالد القاسمي، رئيس دائرة العلاقات الحكومية، وعبد الله سلطان العويس، رئيس غرفة تجارة وصناعة الشارقة وعدد من أعضاء مجلس الإدارة، وخالد بن بطي الهاجري مدير عام الغرفة.",
            "apple-mobile-web-app-capable": "yes",
            rights: "©2021 صحيفة الخليج. All rights reserved.",
            mobileoptimized: "width",
            "og:url":
              "https://www.alkhaleej.ae/2017-02-13/%C2%AB%D8%BA%D8%B1%D9%81%D8%A9-%D8%A7%D9%84%D8%B4%D8%A7%D8%B1%D9%82%D8%A9%C2%BB-%D8%AA%D8%A8%D8%AD%D8%AB-%D8%A2%D9%81%D8%A7%D9%82-%D8%A7%D9%84%D8%AA%D8%B9%D8%A7%D9%88%D9%86-%D9%85%D8%B9-%D9%85%D8%AF%D9%8A%D9%86%D8%A9-%D9%81%D8%B1%D9%88%D8%AA%D8%B3%D9%88%D8%A7%D9%81-%D8%A7%D9%84%D8%A8%D9%88%D9%84%D9%86%D8%AF%D9%8A%D8%A9/%D8%A7%D9%82%D8%AA%D8%B5%D8%A7%D8%AF-%D9%85%D8%AD%D9%84%D9%8A",
          },
        ],
        cse_image: [
          {
            src: "https://www.alkhaleej.ae/sites/default/files/styles/social_large/public/migrated/b32b0f22-16e7-4bdf-9c09-8cf8d24fecc7.jpg?itok=GKbqSqWb",
          },
        ],
      },
    },
  ],
};
