import Head from "next/head";
import Image from "next/image";
import { useRef } from "react";
import Body from "../components/FrontPage/Body";
import Footer from "../components/FrontPage/Footer";
import Header from "../components/FrontPage/Header";
import { useRouter } from "next/router";
export default function Home() {
  const text = useRef("");
  const router = useRouter();
  const search = (e) => {
    e.preventDefault();
    const { value } = text.current;
    if (!value) return;
    router.push(`/search?term=${value}`);
    text.current.value = "";
  };
  return (
    <div className="flex flex-col justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      <Body search={search} text={text} />
      <Footer />
      {/* body */}
    </div>
  );
}
